version: "3.7"

networks:
  server:
    external: false

services:
  db:
    image: postgres:14
    container_name: local_pgdb
    networks:
      - server
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    networks:
      - server
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@platform.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z.hotfix.e6c50dc4c
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - ./files:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    networks:
      - server

  auth:
    image: nailz2k/auth
    container_name: auth
    ports:
      - "3005:3005"
    networks:
      - server
    environment:
      TYPEORM_HOST: ${HOST}
      TYPEORM_USERNAME: ${PG_USER}
      TYPEORM_PASSWORD: ${PG_PASSWORD}
      TYPEORM_DATABASE: users
      TYPEORM_PORT: ${TYPEORM_PORT}
      PORT: 3005
    depends_on:
      - db

  storage:
    image: nailz2k/minio-storage
    container_name: minio-storage
    ports:
      - "3002:3002"
    networks:
      - server
    environment:
      TYPEORM_HOST: ${HOST}
      TYPEORM_USERNAME: ${PG_USER}
      TYPEORM_PASSWORD: ${PG_PASSWORD}
      TYPEORM_DATABASE: storage
      MINIO_HOST: ${HOST}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      PORT: 3002
    depends_on:
      - db
      - minio

  messanger:
    image: nailz2k/ws-messenger
    container_name: ws-messanger
    ports:
      - "3001:3001"
      - "3333:3333"
    networks:
      - server
    environment:
      TYPEORM_HOST: ${HOST}
      TYPEORM_USERNAME: ${PG_USER}
      TYPEORM_PASSWORD: ${PG_PASSWORD}
      TYPEORM_DATABASE: storage
      TYPEORM_PORT: ${TYPEORM_PORT}
      PORT: 3001
      WS_PORT: 3333
    depends_on:
      - db
      - minio

  posts:
    image: nailz2k/posts
    container_name: posts
    ports:
      - "3004:3004"
    networks:
      - server
    environment:
      TYPEORM_HOST: ${HOST}
      TYPEORM_USERNAME: ${PG_USER}
      TYPEORM_PASSWORD: ${PG_PASSWORD}
      TYPEORM_DATABASE: posts
      TYPEORM_PORT: ${TYPEORM_PORT}
      PORT: 3004
    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data:
